@baseURL = http://localhost:3000

###
# Get votes
GET {{baseURL}}/vote?period=

###
# Get vote candidates
GET {{baseURL}}/vote/award-winning

###
# Get vote leaderboard
GET {{baseURL}}/vote/leaderboard?password=vnmg-ranking-backend&period=&top=

###
# Submit a vote
POST {{baseURL}}/vote
Content-Type: application/json

{
  "favoriteAdaptations": ["2afbc2cb-cf38-4562-9d1a-315f5b0c0cfe", "5c46e237-042d-41cf-b127-7f767054c1e7"],
  "favoriteAwardWinnings": ["ad06790a-01e3-400c-a449-0ec152d6756a", "c753ba3c-d403-4af8-80e6-f453e2f9b591"],
  "favoriteMonthlyPublisheds": ["233d5273-7153-4b6c-8b03-baa045c10c88", "d5fc7efb-2d28-490f-bb0e-2c8aefdd6b85"],
  "favoriteRecommendeds": ["c8aebcc7-678e-4682-a727-48febbc325fd"],
  "userInfo": {
    "gender": "male",
    "age": 23
  },
  "token": "10000000-aaaa-bbbb-cccc-000000000001"
}
